#!/bin/bash

# Wait CUPS start
while ! curl -sk localhost:631 &>/dev/null; do
  sleep 1
done

/opt/airprint-generate.py -d /avahi

inotifywait -m /config/cups/ppd -e create -e moved_to -e close_write|
  while read path action file; do
    echo "Printer ${file} modified, reloading Avahi services."
    /opt/airprint-generate.py -d /avahi
  done

